version: '3.7'

services:
   app:
      image: app_segura24
      #build: ./contenedor
      volumes:
         - ./Docker/App:/code
      depends_on:
         - db
      environment:
         DJANGO_KEY: ${DJANGO_KEY}
         DB_NAME: ${DB_NAME}
         DB_USER: ${DB_USER}
         DB_PASSWORD: ${DB_PASSWORD}
         DB_HOST: db
         DB_PORT: ${DB_PORT}
      deploy:
         resources:
            limits:
               cpus: "3"
               memory: "1024M"                 

   db:
      image: mariadb
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
         MYSQL_DATABASE: ${DB_NAME}
      volumes:
         - ./data:/var/lib/mysql

   nginx:
      image: nginx
      restart: always
      ports:
         - 80:80
         - 443:443
      volumes:
         - ./nginx:/etc/nginx/conf.d
         - ./Docker/App/static:/static         
